# Generated by Django 5.1.2 on 2024-10-29 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API_CONNECTIONS', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'managed': False},
        ),
    ]
