# Generated by Django 5.1.2 on 2024-10-29 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API_CONNECTIONS', '0002_alter_history_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='history',
            table='saved_trades',
        ),
    ]
